'use client';
import type { Dispatch,SetStateAction } from 'react';
import type { Filters } from './AdminDashboard';
import type { Data } from './shared';
import { money,label } from './shared';
import type { AnalyticsData } from '@/types/analytics';
const statusNames=['pending','confirmed','preparing','ready','completed','cancelled'];
const dayLabel=(date:string)=>new Date(`${date}T00:00:00Z`).toLocaleDateString('en-IN',{timeZone:'UTC',day:'numeric',month:'short'});
function Bars({title,values,empty='No records in this period.'}:{title:string;values:[string,number][];empty?:string}) {
 const max=Math.max(1,...values.map(([,n])=>n));
 return <article className="ma-panel"><h2>{title}</h2>{values.some(([,n])=>n>0)?<div className="ma-analytics-bars">{values.map(([name,n])=><div className="ma-chart-row" key={name}><span>{name}</span><div><i style={{width:`${n/max*100}%`}}/></div><strong>{n}</strong></div>)}</div>:<><p className="ma-muted">{empty}</p>{values.map(([name,n])=><div className="ma-chart-row" key={name}><span>{name}</span><div/><strong>{n}</strong></div>)}</>}</article>;
}
function Trend({title,days,field}:{title:string;days:AnalyticsData['trend'];field:'orders'|'subtotal'}) {
 const max=Math.max(1,...days.map(d=>d[field])),left=48,right=342,top=22,bottom=165;
 const points=days.map((d,i)=>({x:days.length===1?(left+right)/2:left+i*(right-left)/(days.length-1),y:bottom-d[field]/max*(bottom-top)}));
 const path=points.map((p,i)=>`${i?'L':'M'}${p.x},${p.y}`).join(' ');
 const tickIndices=[...new Set([0,Math.floor((days.length-1)/3),Math.floor(2*(days.length-1)/3),days.length-1])];
 const total=days.reduce((sum,d)=>sum+d[field],0);
 if (!days.some(d=>d.orders>0)) return <article className="ma-panel ma-trend"><h2>{title}</h2><p className="ma-muted">No order data for this period.</p></article>;
 const axis=(v:number)=>field==='subtotal'?(v>=1000?`₹${(v/1000).toFixed(1)}k`:`₹${Math.round(v)}`):String(Math.round(v));
 return <article className="ma-panel ma-trend"><div className="ma-trend-title"><h2>{title}</h2><strong>{field==='subtotal'?money(total):total}</strong></div><p className="ma-muted">{field==='orders'?'Actual orders created · excludes drafts':'Confirmed through completed orders · excludes pending/cancelled'}</p><svg viewBox="0 0 360 210" role="img" aria-label={`${title}: ${field==='subtotal'?money(total):total} from ${days[0]?.date} to ${days.at(-1)?.date}`}>
 {[0,.5,1].map(t=><g key={t}><line x1={left} x2={right} y1={bottom-t*(bottom-top)} y2={bottom-t*(bottom-top)} className="ma-grid-line"/><text x={left-8} y={bottom-t*(bottom-top)+4} textAnchor="end">{axis(t*max)}</text></g>)}
 {points.length>1&&<path d={`${path} L${points.at(-1)!.x},${bottom} L${points[0].x},${bottom} Z`} className="ma-trend-fill"/>}<path d={path} className="ma-trend-line"/>{points.length<=31&&points.map((p,i)=><circle key={days[i].date} cx={p.x} cy={p.y} r="2.5"><title>{dayLabel(days[i].date)}: {field==='subtotal'?money(days[i][field]):days[i][field]}</title></circle>)}
 {tickIndices.filter(i=>i>=0).map(i=><text key={i} x={points[i]?.x} y="191" textAnchor={i===0?'start':i===days.length-1?'end':'middle'}>{dayLabel(days[i].date)}</text>)}
 </svg><details><summary>View daily values</summary><div className="ma-daily-values">{days.map(day=><div key={day.date}><span>{dayLabel(day.date)}</span><strong>{field==='subtotal'?money(day[field]):day[field]}</strong></div>)}</div></details></article>;
}
export function Analytics({data,filters,setFilters,busy,error}:{data:Data;filters:Filters;setFilters:Dispatch<SetStateAction<Filters>>;busy:boolean;error:boolean}) {
 const a=data.analytics;
 const update=(key:keyof Filters,value:string)=>setFilters(f=>({...f,[key]:value}));
 const enquiries=Object.entries(a?.enquiries||{}).map(([type,n]):[string,number]=>[type==='unclassified'?'Type not recorded':label(type),n]);
 return <><section className="ma-filters ma-analytics-filter" aria-label="Analytics date filters"><label>Date range<select value={filters.period} onChange={e=>update('period',e.target.value)}><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="week">Last 7 days</option><option value="last30">Last 30 days</option><option value="month">This month</option><option value="custom">Custom range</option></select></label>{filters.period==='custom'&&<><label>From<input type="date" value={filters.from} max={filters.to||undefined} onChange={e=>update('from',e.target.value)}/></label><label>To<input type="date" value={filters.to} min={filters.from||undefined} onChange={e=>update('to',e.target.value)}/></label></>}<p>Dates use India Standard Time. Counts include archived records and follow their creation date.</p></section>
 {!busy&&!error&&a&&<><p className="ma-muted">{dayLabel(a.from)} – {dayLabel(a.to)} · Supabase records · Confirmed includes preparing, ready and completed.</p><div className="ma-stats ma-analytics-stats">{[['Total orders',a.totals.orders],['Confirmed orders',a.totals.confirmed],['Completed orders',a.totals.completed],['Menu subtotal',money(a.totals.subtotal)],['Website drafts',a.totals.drafts],['Reservations',a.totals.reservations],['Enquiries',a.totals.enquiries]].map(([name,value])=><article className="ma-stat" key={name}><div>{name}</div><strong>{value}</strong></article>)}</div>{a.totals.unpricedOrders>0&&<p className="ma-notice">{a.totals.unpricedOrders} confirmed orders have no verified subtotal and are excluded from the amount.</p>}
 <div className="ma-overview-grid"><Trend title="Orders over time" days={a.trend} field="orders"/><Trend title="Menu subtotal over time" days={a.trend} field="subtotal"/></div>
 <div className="ma-overview-grid"><Bars title="Order status" values={statusNames.map(s=>[label(s),a.statuses[s]||0])}/><Bars title="Order source" values={[['Website',a.sources.website||0],['WhatsApp',a.sources.whatsapp||0]]}/></div>
 {!data.cloudConfigured&&<p className="ma-notice">Meta WhatsApp Cloud API is not configured. Manually sent WhatsApp messages do not appear here yet. These counts reflect stored records only.</p>}
 <div className="ma-overview-grid"><Bars title="Fulfilment" values={[['Pickup',a.fulfilment.pickup||0],['Dine-in',a.fulfilment['dine-in']||0],...(data.deliveryEnabled||a.fulfilment.delivery?[['Delivery',a.fulfilment.delivery||0] as [string,number]]:[])]}/><Bars title="Reservation requests" empty="No reservation data for this period." values={[['Pending',a.reservations.pending||0],['Confirmed',a.reservations.confirmed||0],['Completed',a.reservations.completed||0],['Declined',a.reservations.declined||0],['Cancelled',a.reservations.cancelled||0]]}/></div>
 <article className="ma-panel"><h2>Top ordered items</h2><p className="ma-muted">Top 10 servings by quantity in confirmed through completed orders. No draft, pending or cancelled items.</p>{a.topItems.length?<div className="ma-top-items"><div className="ma-top-item ma-top-item-head"><span>Item / Serving</span><span>Quantity</span><span>Menu subtotal</span></div>{a.topItems.map(item=><div className="ma-top-item" key={`${item.id}-${item.name}-${item.variant}`}><span><strong>{item.name}</strong><small>{item.variant}</small></span><span>{item.quantity}</span><strong>{money(item.subtotal)}</strong></div>)}</div>:<p className="ma-muted">No confirmed item data in this period.</p>}</article>
 <div className="ma-overview-grid"><Bars title="Enquiry types" values={enquiries} empty="No enquiry data for this period."/><Bars title="Enquiry status" empty="No enquiry data for this period." values={['new','contacted','resolved','archived'].map(s=>[label(s),a.enquiryStatuses[s]||0])}/></div><div className="ma-overview-grid"><article className="ma-panel"><h2>Website draft activity</h2><p className="ma-muted">Drafts created in this period; current lifecycle state.</p><dl><dt>Created</dt><dd>{a.drafts.created}</dd><dt>Active</dt><dd>{a.drafts.active}</dd><dt>Expired</dt><dd>{a.drafts.expired}</dd><dt>Continued</dt><dd>{a.drafts.consumed}</dd><dt>Linked confirmed orders</dt><dd>{a.drafts.linkedConfirmed}</dd><dt>Conversion</dt><dd>{a.drafts.created?`${(100*a.drafts.linkedConfirmed/a.drafts.created).toFixed(1)}%`:'—'}</dd></dl><p className="ma-muted">Conversion uses the stored orders.draft_token link and confirmed-through-completed status, including orders confirmed after this date range.</p></article></div></>}
 </>;
}
