'use client';
import Image from 'next/image';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {motion,useScroll,useTransform,useReducedMotion,useMotionValueEvent} from 'motion/react';
import {ArrowUpRight} from 'lucide-react';
import {foodVisuals,visualSettings,type FoodVisual} from '@/data/food-visuals';
import {findItem,formatPrice,type MenuItem} from '@/data/menu-data';
import {Reveal,DietIcon,Parallax} from '@/components/ui/Motion';
import {MenuItemModal} from '@/components/menu/MenuItemModal';
const featured=[{id:'mozza-italia-spl',image:'chickenPizza',label:'THE SIGNATURE SLICE'},{id:'chicken-zinger-burger',image:'burger',label:'BIG ON CRUNCH'},{id:'chittimutyalu-chicken-ghee-pulav',image:'chittimutyalu',label:'A SPOONFUL OF COMFORT'},{id:'cheesy-loaded-fries',image:'fries',label:'MADE TO SHARE'}] as const;
export function SignatureDishes(){const [selected,setSelected]=useState<MenuItem|null>(null);return <section className="section signatures" id="signatures"><Reveal className="section-heading"><div><span className="eyebrow">THE GOOD STUFF</span><h2>MEET YOUR NEXT<br/><span className="serif-accent">favourite.</span></h2></div><Link className="text-link" href="/menu">Explore the full menu <ArrowUpRight/></Link></Reveal><div className="signature-grid">{featured.map((f,i)=>{const item=findItem(f.id);return <Reveal key={f.id} className={`signature-wrap signature-${i}`}><button className="signature-card" onClick={()=>setSelected({...item,image:f.image})}><div className="signature-image"><Image src={foodVisuals[f.image]} fill sizes="(max-width:600px) 78vw, (max-width:1000px) 45vw, 24vw" alt={`Illustrative ${item.name}`}/><span className="signature-index">0{i+1}</span><span className="round-arrow"><ArrowUpRight/></span></div><span className="eyebrow">{f.label}</span><h3><DietIcon diet={item.diet}/>{item.name}</h3><div className="signature-price"><span>From {formatPrice(item.sizes[0].price)}</span><span>{item.sizes[0].label}</span></div></button></Reveal>;})}</div><MenuItemModal item={selected} onClose={()=>setSelected(null)}/></section>;}
const scenes:{number:string;label:string;title:string;accent:string;copy:string;image:FoodVisual;href:string}[]=[
 {number:'01',label:'THE ART OF A GOOD SLICE',title:'STRETCHED.\nSAUCED.\nLOADED.',accent:'BAKED.',copy:'A little sauce. A lot of cheese. Your kind of pizza.',image:'pizza',href:'/menu#veg-pizza'},
 {number:'02',label:'TURN UP THE CRUNCH',title:'CRISPY ON\nTHE OUTSIDE.',accent:'JUICY.',copy:'Where it matters. Wings, tenders and crispy chicken worth gathering around.',image:'chicken',href:'/menu#broasted-chicken'},
 {number:'03',label:'STACKED WITH THE GOOD STUFF',title:'GOOD FOOD.',accent:'GOOD MOOD.',copy:'Meet the Chicken Zinger Burger. A little messy. Every bit worth it.',image:'burgerLayers',href:'/menu#burger'},
 {number:'04',label:'A LITTLE CLOSER TO HOME',title:'COMFORT IN\nEVERY',accent:'SPOONFUL.',copy:'Ghee pulav, warm spices and all the comforting flavours you came for.',image:'rice',href:'/menu#basmathi-ghee-pulav'},
];
function StoryScene({scene,index}:{scene:typeof scenes[number];index:number}){const ref=useRef<HTMLDivElement>(null);const reduce=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const rotate=useTransform(scrollYProgress,[0,1],[-7,7]);const scale=useTransform(scrollYProgress,[0,.5,1],[.92,1.04,.98]);const separation=useTransform(scrollYProgress,[0,.45,.65,1],[0,1,1,0]);return <div ref={ref} className={`story-scene story-${index}`} id={`story-${index}`}><div className="scene-copy"><span className="eyebrow gold">{scene.number} / {scene.label}</span><h2>{scene.title.split('\n').map(t=><span key={t}>{t}<br/></span>)}<em>{scene.accent}</em></h2><p>{scene.copy}</p><Link href={scene.href} className="text-link">Find your flavour <ArrowUpRight/></Link></div><motion.div className="scene-visual" style={reduce?{}:{rotate,scale}}>{index===2&&visualSettings.burgerLayered?<BurgerLayers amount={separation}/>:<Image src={foodVisuals[index===2?'burger':scene.image]} fill sizes="(max-width:700px) 100vw, 60vw" alt={`Illustrative ${scene.image==='rice'?'chicken ghee pulav':scene.image}`}/>} {index===3&&<div className="steam" aria-hidden="true"><i/><i/><i/></div>}</motion.div><span className="scene-watermark" aria-hidden="true">{scene.number}</span></div>;}
function BurgerLayers({amount}:{amount:ReturnType<typeof useTransform<number,number>>}){const reduce=useReducedMotion();return <div className="burger-layers">{[0,1,2,3,4,5].map(i=><BurgerLayer key={i} i={i} amount={amount} reduce={!!reduce}/>)}</div>;}
function BurgerLayer({i,amount,reduce}:{i:number;amount:ReturnType<typeof useTransform<number,number>>;reduce:boolean}){const y=useTransform(amount,[0,1],[(2.5-i)*21,0]);const ranges=[[0,23],[23,37],[37,46],[46,64],[64,75],[75,100]];return <motion.div className="burger-layer" style={{clipPath:`inset(${ranges[i][0]}% 0 ${100-ranges[i][1]}% 0)`,...(reduce?{}:{y})}}><Image src={foodVisuals.burgerLayers} fill sizes="(max-width:700px) 100vw, 55vw" alt={i===0?'Illustrative exploded Chicken Zinger Burger layers':''}/></motion.div>;}
export function FoodStory(){const ref=useRef<HTMLElement>(null);const [stage,setStage]=useState(0);const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});useMotionValueEvent(scrollYProgress,'change',v=>setStage(Math.min(3,Math.floor(v*4))));return <section ref={ref} className="food-story" aria-label="Flavours for every mood"><div className="story-progress" aria-label="Food story chapters">{scenes.map((s,i)=><a key={s.number} href={`#story-${i}`} className={stage===i?'active':''}><span>{s.number}</span><i/></a>)}</div>{scenes.map((s,i)=><StoryScene key={s.number} scene={s} index={i}/>)}</section>;}
export function SweetFinish(){return <section className="sweet-section"><div className="sweet-panel drinks-panel"><div><span className="eyebrow">SIP. SLOW DOWN. REPEAT.</span><h2>KEEP IT<br/><em>cool.</em></h2><Link href="/menu#mojitos" className="text-link">Find your refreshment <ArrowUpRight/></Link></div><Parallax className="sweet-image"><Image src={foodVisuals.drinks} fill sizes="(max-width:700px) 100vw, 50vw" alt="Illustrative mint mojito and chocolate milkshake"/></Parallax></div><div className="sweet-panel dessert-panel"><div><span className="eyebrow">THERE’S ALWAYS ROOM.</span><h2>END ON A<br/><em>sweet note.</em></h2><Link href="/menu#desserts" className="text-link">Something sweet <ArrowUpRight/></Link></div><Parallax className="sweet-image"><Image src={foodVisuals.desserts} fill sizes="(max-width:700px) 100vw, 50vw" alt="Illustrative warm brownie with vanilla ice cream"/></Parallax></div></section>;}
