'use client';
import {useState,type FormEvent} from 'react';
import {ArrowUpRight} from 'lucide-react';
import {whatsappUrl} from '@/config/restaurant';
export function ReservationSection(){const [request,setRequest]=useState<string|null>(null);const [error,setError]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')||'').trim();const mobile=String(data.get('mobile')||'').replace(/\D/g,'');const date=String(data.get('date'));const time=String(data.get('time'));const when=new Date(`${date}T${time}:00+05:30`);if(!name||mobile.length<10||mobile.length>12){setError('Please enter your name and a valid mobile number.');return;}if(when.getTime()<=Date.now()){setError('Please choose a future date and time.');return;}setError('');setRequest(whatsappUrl(`Hello Mozza Italia,\nI would like to reserve a table.\n\nName: ${name}\nMobile: ${data.get('mobile')}\nDate: ${date}\nTime: ${time} (IST)\nGuests: ${data.get('guests')}\n${data.get('message')?`Message: ${data.get('message')}\n`:''}\nPlease confirm availability.`));}
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 return <section className="section reservation" id="reservation"><div><span className="eyebrow gold">GOOD COMPANY DESERVES A TABLE</span><h2>SAVE A SEAT.<br/><em>MAKE A<br/>MOMENT.</em></h2><p>Bring your people. We’ll help with the rest.<br/>Send a table request to our Shadnagar team.</p><span className="reservation-note">A request, not a confirmed booking.<br/>Our team will confirm your table on WhatsApp.</span></div><form onSubmit={submit} onChange={()=>setRequest(null)}><div className="form-grid"><label>Your name<input name="name" required autoComplete="name" placeholder="Name" maxLength={80}/></label><label>Mobile number<input name="mobile" type="tel" required autoComplete="tel" placeholder="Your mobile number" pattern="[+0-9 ()-]{10,18}" maxLength={18}/></label><label>Date<input type="date" name="date" min={today} required/></label><label>Time (IST)<input type="time" name="time" required/></label><label>Guests<select aria-label="Guests" name="guests" defaultValue="2">{[1,2,3,4,5,6,7,8,9,10,11,12].map(n=><option value={n} key={n}>{n} {n===1?'guest':'guests'}</option>)}<option value="13+">13+ guests</option></select></label><label>Anything else? <span>(optional)</span><input name="message" placeholder="A celebration, a preference…" maxLength={500}/></label></div>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button red full" type="submit">Prepare table request <ArrowUpRight size={18}/></button>{request&&<div className="request-ready" role="status"><p>Your request is ready. Open WhatsApp to review and send it to the restaurant.</p><a className="button outline" href={request} target="_blank" rel="noreferrer">Continue to WhatsApp <ArrowUpRight size={18}/></a></div>}<p className="form-privacy">Your details stay in this form until you choose to open WhatsApp. No booking is stored on this website.</p></form></section>;
}
