import test from 'node:test';
import assert from 'node:assert/strict';
import {load} from './ts-loader.mjs';
const session=load('src/lib/server/admin-session.ts');
const security=load('src/lib/server/security.ts');
const auth=load('src/app/api/admin/session/route.ts');
const records=load('src/app/api/admin/records/route.ts');
const listing=load('src/lib/server/admin-data.ts');
const dashboard=load('src/app/api/admin/dashboard/route.ts');
const {dateRange}=load('src/lib/admin-ui.ts');
const original={...process.env};
const realFetch=globalThis.fetch;
function setup(){process.env.NODE_ENV='development';process.env.ADMIN_TEST_USERNAME='test';process.env.ADMIN_TEST_PASSWORD='test';process.env.ADMIN_ORDER_SECRET='qa-only-admin-secret-with-at-least-32-chars';process.env.SUPABASE_URL='https://example.invalid';process.env.SUPABASE_SERVICE_ROLE_KEY='qa-only';}
function req(body,headers={}){return new Request('http://localhost:3000/api/admin/records',{method:'PATCH',headers:{origin:'http://localhost:3000',authorization:`Bearer ${process.env.ADMIN_ORDER_SECRET}`,'content-type':'application/json',...headers},body:JSON.stringify(body)});}
test.afterEach(()=>{globalThis.fetch=realFetch;for(const key of Object.keys(process.env))if(!(key in original))delete process.env[key];Object.assign(process.env,original);});
test('development credentials are configured explicitly; missing config fails closed',()=>{setup();assert.equal(session.validLogin('test','test'),true);assert.equal(session.validLogin('test','wrong'),false);delete process.env.ADMIN_TEST_PASSWORD;assert.equal(session.validLogin('test','test'),false);});
test('production rejects development/test credentials and requires secure configuration',()=>{setup();process.env.NODE_ENV='production';assert.equal(session.validLogin('test','test'),false);process.env.ADMIN_USERNAME='operator';process.env.ADMIN_PASSWORD='a-long-production-example-for-unit-test';assert.equal(session.validLogin('operator',process.env.ADMIN_PASSWORD),true);process.env.ADMIN_PASSWORD='test';assert.equal(session.validLogin('operator','test'),false);});
test('signed session rejects tampering, expiry and credential rotation',()=>{setup();const token=session.createSession();const r=t=>new Request('http://localhost',{headers:{cookie:`mozza_staff=${t}`}});assert.equal(session.sessionAuthorized(r(token)),true);assert.equal(session.sessionAuthorized(r(token+'x')),false);assert.equal(session.sessionAuthorized(r('1.'+token.split('.').slice(1).join('.'))),false);process.env.ADMIN_TEST_PASSWORD='changed';assert.equal(session.sessionAuthorized(r(token)),false);});
test('session cookies are HttpOnly, session-scoped, SameSite strict and secure in production',()=>{setup();const h=session.cookieHeader('example');assert.match(h,/HttpOnly/);assert.match(h,/SameSite=Strict/);assert.doesNotMatch(h,/Max-Age/);process.env.NODE_ENV='production';assert.match(session.cookieHeader('example'),/Secure/);assert.match(session.cookieHeader(''),/Max-Age=0/);});
test('session login and logout endpoints enforce origin and issue/clear cookies',async()=>{setup();let r=await auth.POST(new Request('http://localhost/api/admin/session',{method:'POST',headers:{origin:'https://other.invalid'},body:'{}'}));assert.equal(r.status,403);r=await auth.POST(new Request('http://localhost/api/admin/session',{method:'POST',headers:{origin:'http://localhost'},body:JSON.stringify({username:'test',password:'test'})}));assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);r=await auth.DELETE(new Request('http://localhost/api/admin/session',{method:'DELETE',headers:{origin:'http://localhost'}}));assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
test('all new APIs reject anonymous access without touching the database',async()=>{setup();globalThis.fetch=()=>{throw Error('Network must not be called');};assert.equal((await dashboard.GET(new Request('http://localhost/api/admin/dashboard'))).status,401);assert.equal((await records.PATCH(req({}, {authorization:''}))).status,401);assert.equal(security.adminAuthorized(new Request('http://localhost')),false);});
test('management writes enforce origin, development-only delete and DELETE confirmation',async()=>{setup();globalThis.fetch=()=>{throw Error('Network must not be called');};assert.equal((await records.PATCH(req({}, {origin:'https://other.invalid'}))).status,403);const body={section:'orders',id:'00000000-0000-0000-0000-000000000001',action:'delete'};assert.equal((await records.PATCH(req(body))).status,403);process.env.NODE_ENV='production';assert.equal((await records.PATCH(req({...body,confirmation:'DELETE'}))).status,403);});
test('archive/delete guard protects active orders and unarchived test records',async()=>{setup();globalThis.fetch=async()=>Response.json([{id:'id',status:'pending'}]);const body={section:'orders',id:'00000000-0000-0000-0000-000000000001'};assert.equal((await records.PATCH(req({...body,action:'archive'}))).status,409);assert.equal((await records.PATCH(req({...body,action:'delete',confirmation:'DELETE'}))).status,409);});
test('reservation status update uses guarded PATCH and persists selected status',async()=>{setup();const calls=[];globalThis.fetch=async(url,options)=>{calls.push({url,options});return Response.json([{id:'id',status:calls.length===1?'confirmed':'completed'}]);};const r=await records.PATCH(req({section:'reservations',id:'00000000-0000-0000-0000-000000000001',action:'status',status:'completed'}));assert.equal(r.status,200);assert.match(calls[1].url,/status=eq.confirmed/);assert.equal(JSON.parse(calls[1].options.body).status,'completed');});
test('bounded server pagination and item/name search preserve all filters',()=>{const q=listing.buildListQuery(new URLSearchParams({section:'orders',page:'2',size:'25',search:'Margarita',source:'website',status:'confirmed',fulfilment:'pickup',from:'2026-09-26',sort:'highest'}));const decoded=decodeURIComponent(q.path);assert.match(decoded,/offset=25/);assert.match(decoded,/limit=25/);assert.match(decoded,/snapshot->>lines.ilike/);assert.match(decoded,/source.eq.website/);assert.match(decoded,/status.eq.confirmed/);assert.match(decoded,/subtotal.desc/);assert.match(decoded,/05:30/);assert.equal(listing.buildListQuery(new URLSearchParams({size:'9999'})).size,25);assert.throws(()=>listing.buildListQuery(new URLSearchParams({section:'__proto__'})));});
test('history archive filtering and draft projection avoid internal hashes',()=>{const path=decodeURIComponent(listing.buildListQuery(new URLSearchParams({section:'history',archived:'only'})).path);assert.match(path,/archived_at.not.is.null/);const draft=listing.buildListQuery(new URLSearchParams({section:'drafts'})).path;assert.doesNotMatch(draft,/request_hash|request_key/);assert.match(decodeURIComponent(draft),/consumed_at.is.null/);});
test('IST date boundaries, last-seven-days and month boundaries are correct',()=>{assert.deepEqual(dateRange('today',new Date('2026-09-25T20:00:00Z')),{from:'2026-09-26',to:'2026-09-26'});assert.deepEqual(dateRange('week',new Date('2026-09-26T12:00:00Z')),{from:'2026-09-20',to:'2026-09-26'});assert.deepEqual(dateRange('month',new Date('2026-09-26T12:00:00Z')),{from:'2026-09-01',to:'2026-09-26'});});
test('database errors are sanitized and missing migration gives actionable guidance',()=>{assert.match(listing.adminError(new listing.AdminDatabaseError(400,'42703')),/202609260002/);assert.match(listing.adminError(new listing.AdminDatabaseError(401,'42501')),/service-role/);assert.doesNotMatch(listing.adminError(new Error('SECRET_TOKEN')),/SECRET_TOKEN/);});
