import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {load} from './ts-loader.mjs';
const realFetch=globalThis.fetch;
for(const key of Object.keys(process.env)) if(/^(SUPABASE_|WHATSAPP_)/.test(key)) delete process.env[key];
const clean={...process.env};
afterEach(()=>{globalThis.fetch=realFetch;for(const key of Object.keys(process.env))if(!(key in clean))delete process.env[key];Object.assign(process.env,clean);});
const config=load('src/config/restaurant.ts'),u=load('src/lib/order-utils.ts'),w=load('src/lib/website-requests.ts'),engine=load('src/lib/whatsapp/engine.ts');
const orders=load('src/app/api/orders/route.ts'),requests=load('src/app/api/website-requests/route.ts'),server=load('src/lib/server/config.ts');
const {menuItems,menuCategories}=load('src/data/menu-data.ts'),{getMenuItemPhoto}=load('src/data/menu-images.ts');
const contacts={hyderabad:'918712357688',shadnagar:'919949799488',jadcherla:'919951047424',guntur:'919246769769'};
const items=[{menuItemId:'margarita',variant:0,quantity:2},{menuItemId:'chicken-zinger-burger',variant:0,quantity:1},{menuItemId:'veg-fingers',variant:0,quantity:3}];
const customer={name:'Branch QA',phone:'9000000081'};
const order=branch=>u.validateCheckout({branch,items,fulfilment:'pickup',customer});
const tomorrow=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
const reservation=branch=>({kind:'reservation',form:'full',branch,...customer,date:tomorrow,time:'19:30',guests:4});
const enquiry=branch=>({kind:'enquiry',branch,...customer,eventType:'Bulk Food Order',eventDate:tomorrow,guestRange:'21–30',service:'Pickup',food:'Mixed'});
const req=(path,body)=>new Request('http://localhost'+path,{method:'POST',headers:{origin:'http://localhost','idempotency-key':'branch-test-key-0000000001'},body:JSON.stringify(body)});
function verify(url,branch){const parsed=new URL(url);assert.equal(parsed.hostname,'wa.me');assert.equal(parsed.pathname,'/'+contacts[branch]);assert.ok(parsed.searchParams.get('text').includes('Outlet: '+config.resolveBranch(branch).name));}
function database(){Object.assign(process.env,{SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-only'});}
for(const branch of Object.keys(contacts)){
 test(branch+': mapping, item/contact/location actions and invalid-safe URL',()=>{assert.equal(config.resolveBranch(branch).whatsapp,contacts[branch]);verify(config.itemOrderUrl('Margarita','Regular',branch),branch);for(const intent of ['order','reservation','catering','support','location'])verify(config.whatsappIntentUrl(intent,branch),branch);});
 test(branch+': persisted cart, trusted totals and all checkout variants',()=>{const cart=u.restoreCart(JSON.stringify({branch,items}));assert.equal(cart.branch,branch);assert.equal(cart.items.length,3);assert.equal(order(branch).subtotal,905);assert.equal(u.changeQuantity(cart,1,2).branch,branch);assert.equal(u.emptyCart(branch).branch,branch);for(const fulfilment of ['pickup','dine-in'])verify(config.whatsappUrl(branch,u.orderMessage(u.validateCheckout({...order(branch),fulfilment}))),branch);});
 test(branch+': order fallback and stored draft routing',async()=>{let response=await orders.POST(req('/api/orders',order(branch)));verify((await response.json()).whatsappUrl,branch);database();let stored;globalThis.fetch=async(url,options)=>{assert.match(url,/rpc\/create_order_draft$/);stored=JSON.parse(options.body).p_checkout;return Response.json({token:'MI-DRAFT-TEST'});};response=await orders.POST(req('/api/orders',order(branch)));const body=await response.json();assert.equal(body.mode,'stored-fallback');assert.equal(stored.branch,branch);assert.equal(stored.subtotal,905);verify(body.whatsappUrl,branch);});
 test(branch+': reservation, planner and catering persist matching outlet before handoff',async()=>{database();for(const payload of [reservation(branch),{...reservation(branch),form:'planner',name:undefined,phone:undefined},enquiry(branch)]){let stored;globalThis.fetch=async(url,options)=>{assert.match(url,/rpc\/create_website_request$/);stored=JSON.parse(options.body).p_request;return Response.json({reference:'QA-REF'});};const response=await requests.POST(req('/api/website-requests',payload));assert.equal(response.status,200);verify((await response.json()).whatsappUrl,branch);assert.equal(stored.branch,branch);}});
 test(branch+': bot order/reset/reservation/catering retains outlet',()=>{const now=new Date();const phone='919000000081';let s=engine.initialSession(branch);const run=inputs=>{let result;for(const input of inputs){result=engine.transition(s,input,phone,now);s=result.session;}return result;};assert.match(run(['Hi']).replies[0].text,new RegExp(config.resolveBranch(branch).name));run(['order']);for(const [index,line] of items.entries()){if(index)run(['more']);const cat=menuCategories.find(c=>c.items.some(i=>i.id===line.menuItemId));run(['category:'+cat.id,'item:'+line.menuItemId,'variant:'+line.variant,String(line.quantity)]);}const review=run(['checkout','pickup','Branch QA']);assert.match(review.replies[0].text,new RegExp(config.resolveBranch(branch).name));const final=run(['confirm']);assert.equal(final.effect.checkout.branch,branch);assert.equal(u.validateCheckout(final.effect.checkout).subtotal,905);run(['reset']);assert.equal(s.cart.branch,branch);const booking=run(['reserve',tomorrow,'19:30','4','Branch QA','skip','confirm']);assert.equal(booking.effect.reservation.branch,branch);run(['reset']);assert.equal(run(['catering','Branch QA',tomorrow,'20','Birthday','skip']).effect.details.branch,branch);});
}
test('unknown outlets fail closed for every URL and data boundary',async()=>{for(const value of ['unknown','', 'Hyderabad<script>']){assert.throws(()=>config.whatsappUrl(value,'hello'));assert.throws(()=>u.emptyCart(value));assert.throws(()=>w.validateWebsiteRequest(reservation(value)));assert.equal((await orders.POST(req('/api/orders',{...order('hyderabad'),branch:value}))).status,400);}});
test('all menu photos resolve to existing assets, including requested category coverage',()=>{for(const item of menuItems){const photo=getMenuItemPhoto(item);assert.ok(fs.existsSync('public'+photo.src),item.id);assert.ok(photo.alt);}for(const name of ['Margarita','Chicken Zinger Burger','Veg Fingers'])assert.ok(menuItems.find(i=>i.name===name));assert.equal(getMenuItemPhoto(menuItems.find(i=>i.id==='veg-fingers')).src,'/food/items/veg-fingers.webp');});
test('non-live outlets never receive a short bot token, even with global Meta credentials',async()=>{database();Object.assign(process.env,{WHATSAPP_PHONE_NUMBER_ID:'fake-id',WHATSAPP_ACCESS_TOKEN:'test-only',WHATSAPP_API_VERSION:'v99.0',WHATSAPP_APP_SECRET:'test-only',WHATSAPP_VERIFY_TOKEN:'test-only'});globalThis.fetch=async()=>Response.json({token:'MI-DRAFT-TEST'});for(const branch of ['hyderabad','jadcherla','guntur']){const r=await orders.POST(req('/api/orders',order(branch)));const b=await r.json();assert.equal(b.mode,'stored-fallback');verify(b.whatsappUrl,branch);assert.match(new URL(b.whatsappUrl).searchParams.get('text'),/Margarita/);assert.equal(server.cloudReady(branch),false);}assert.equal(server.cloudReady('shadnagar'),true);assert.equal(server.metaConfig('hyderabad').accessToken,undefined);});
test('draft presented to the wrong receiving outlet cannot be resumed',async()=>{const {processIncoming}=load('src/lib/whatsapp/processor.ts');let saved;const store={seen:async()=>false,session:async()=>undefined,draft:async()=>order('guntur'),commit:async args=>{saved=args;return {};},flush:async()=>{}};await processIncoming({id:'test',phone:'919000000081',input:'MI-DRAFT-'+'A'.repeat(32),timestamp:new Date().toISOString(),branch:'shadnagar'},store);assert.equal(saved.p_effect,null);assert.equal(saved.p_session.cart.items.length,0);assert.match(saved.p_replies[0].text,/belongs to Guntur/);});
