import {test} from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {load} from './ts-loader.mjs';
// Explicitly isolate tests from any credentials inherited by the test process.
for (const key of ['SUPABASE_URL','SUPABASE_SERVICE_ROLE_KEY','WHATSAPP_ACCESS_TOKEN','WHATSAPP_PHONE_NUMBER_ID','WHATSAPP_APP_SECRET','WHATSAPP_VERIFY_TOKEN','WHATSAPP_API_VERSION','ADMIN_ORDER_SECRET']) delete process.env[key];
const u=load('src/lib/order-utils.ts');const e=load('src/lib/whatsapp/engine.ts');const security=load('src/lib/server/security.ts');const client=load('src/lib/whatsapp/client.ts');const {processIncoming}=load('src/lib/whatsapp/processor.ts');const {menuItems,menuCategories}=load('src/data/menu-data.ts');
const phone='919876543210';const pizza=menuItems.find(i=>i.id==='margarita');const line={menuItemId:pizza.id,variant:0,quantity:2};const cart={branch:'shadnagar',items:[line]};const checkout={...cart,fulfilment:'pickup',customer:{name:'Test Customer',phone}};const now=new Date('2026-09-26T09:00:00Z');
function chat(inputs,session=e.initialSession()){let result;for(const input of inputs){result=e.transition(session,input,phone,now);session=result.session;}return result;}
const category=menuCategories.find(c=>c.items.some(i=>i.id===pizza.id)).id;
const pizzaFlow=['Hi','order',`category:${category}`,`item:${pizza.id}`,'variant:0','2'];
test('trusted prices ignore forged fields and compute totals',()=>{const order=u.validateCheckout({...checkout,subtotal:1,lines:[{unitPrice:1}],items:[{...line,unitPrice:1}]});assert.equal(order.subtotal,pizza.sizes[0].price*2);assert.equal(order.lines[0].unitPrice,pizza.sizes[0].price);});
test('cart quantities, merge, removal and variants',()=>{let c=u.addLine(cart,{...line,quantity:1});assert.equal(c.items[0].quantity,3);c=u.changeQuantity(c,0,1);assert.equal(c.items[0].quantity,1);c=u.addLine(c,{...line,variant:1,quantity:2});assert.equal(c.items.length,2);assert.equal(u.validateCart({...c,items:[]}).items.length,0);assert.throws(()=>u.addLine(c,{...line,quantity:20}));});
test('invalid quantity, menu, variant and outlet rejected',()=>{for(const quantity of [0,-1,21,1.5,'2',NaN])assert.throws(()=>u.resolveLine({...line,quantity}));assert.throws(()=>u.resolveLine({...line,menuItemId:'missing'}));assert.throws(()=>u.resolveLine({...line,variant:900}));assert.throws(()=>u.validateCart({...cart,branch:'hyderabad'}));assert.throws(()=>u.validateCheckout({...checkout,fulfilment:'delivery'}));});
test('unknown, MRP and manually flagged prices never produce a total',()=>{for(const item of menuItems.filter(i=>i.manualVerification||i.sizes.some(s=>s.price===null||s.label==='MRP'))){const variant=item.sizes.findIndex(s=>s.price===null||s.label==='MRP');const order=u.validateCheckout({...checkout,items:[{menuItemId:item.id,variant:Math.max(0,variant),quantity:1}]});assert.equal(order.subtotal,null);assert.match(u.orderMessage(order),/Price confirmation required/);}});
test('versioned storage recovery and repricing',()=>{assert.match(u.CART_KEY,/-v1$/);assert.deepEqual(u.restoreCart('{broken'),u.emptyCart());assert.deepEqual(u.restoreCart(JSON.stringify({...cart,items:[{...line,menuItemId:'removed'}]})),u.emptyCart());assert.deepEqual(u.restoreCart(JSON.stringify(cart)),cart);});
test('Indian phone normalization',()=>{for(const input of ['9876543210','+91 98765-43210','(91) 9876543210'])assert.equal(u.normalizePhone(input),phone);for(const input of ['123','1234567890','919876543210oops'])assert.throws(()=>u.normalizePhone(input));});
test('structured multi-item message contains servings, quantities and customer',()=>{const order=u.validateCheckout({...checkout,items:[line,{menuItemId:'chicken-zinger-burger',variant:1,quantity:1}]});const message=u.orderMessage(order);assert.match(message,/Order Summary/);assert.match(message,/Qty: 2/);assert.match(message,/Chicken Zinger Burger/);assert.match(message,/Test Customer/);assert.match(message,/Pay at restaurant/);assert.doesNotMatch(message,/menuItemId|variant:/);});
test('random public references and 128-bit draft capability',()=>{const ids=new Set(Array.from({length:1000},()=>security.publicId('MI',now)));assert.equal(ids.size,1000);assert.match([...ids][0],/^MI-20260926-[A-F0-9]{12}$/);assert.match(security.draftToken(),/^MI-DRAFT-[A-F0-9]{32}$/);});
test('category pagination obeys Meta bounds and covers categories',()=>{let state=chat(['order']).session;const ids=new Set();for(let page=0;page<4;page++){const result=e.transition(state,`categories:${page}`,phone,now);assert.ok(result.replies[0].choices.length<=10);for(const c of result.replies[0].choices)if(c.id.startsWith('category:'))ids.add(c.id);}assert.equal(ids.size,menuCategories.length);});
test('direct order selects item, variant, quantity and accumulates cart',()=>{const first=chat(pizzaFlow);assert.equal(first.session.state,'ORDER_CART');assert.equal(first.session.cart.items[0].quantity,2);const second=chat(['more',`category:${category}`,`item:${pizza.id}`,'variant:1','1'],first.session);assert.equal(second.session.cart.items.length,2);assert.equal(second.session.cart.items[0].quantity,2);});
test('bot rejects stale selections and quantity without losing cart',()=>{const start=chat(pizzaFlow).session;const qty=chat(['more',`category:${category}`,`item:${pizza.id}`,'variant:0'],start).session;assert.equal(chat(['21'],qty).session.state,'ORDER_QUANTITY');assert.deepEqual(chat(['21'],qty).session.cart,start.cart);const invalid=chat(['more',`category:${category}`,'item:not-in-category'],start);assert.equal(invalid.session.state,'ORDER_ITEM');});
test('bot cart edit, remove and checkout confirmation',()=>{let result=chat(pizzaFlow);result=chat(['edit','edit:0','3','checkout','pickup','Test Customer'],result.session);assert.equal(result.session.state,'ORDER_REVIEW');assert.equal(result.session.cart.items[0].quantity,3);assert.equal(result.effect,undefined);result=chat(['confirm'],result.session);assert.equal(result.effect.type,'order');assert.equal(result.session.state,'ORDER_CREATED');assert.equal(chat(['confirm'],result.session).effect,undefined);const removed=chat(['edit','edit:0','0'],chat(pizzaFlow).session);assert.equal(removed.session.cart.items.length,0);assert.equal(chat(['checkout'],removed.session).session.state,'ORDER_CART');});
test('draft continuation keeps items, source, details and confirmation',()=>{const result=e.resumeDraft(e.initialSession(),checkout,'MI-DRAFT-ABC');assert.equal(result.session.state,'ORDER_REVIEW');assert.equal(result.session.cart.items[0].quantity,2);const final=chat(['confirm'],result.session);assert.equal(final.effect.source,'website');assert.equal(final.effect.draftToken,'MI-DRAFT-ABC');});
test('reservation date parsing, validation and pending confirmation',()=>{assert.equal(e.parseDate('26 Sep',now),'2026-09-26');assert.throws(()=>e.parseDate('2026-02-30',now));assert.equal(e.parseTime('8:30 PM'),'20:30');assert.throws(()=>e.parseTime('25:00'));const review=chat(['reserve','26 Sep','8:30 PM','4 guests','Test Customer','skip']);assert.equal(review.session.state,'RESERVATION_CONFIRM');assert.match(review.replies[0].text,/Subject to staff confirmation/);assert.equal(review.effect,undefined);assert.equal(chat(['confirm'],review.session).effect.type,'reservation');});
test('staff handoff suppresses automation until explicit RESET',()=>{const result=chat(['staff']);assert.equal(result.effect.type,'handoff');assert.equal(chat(['Hi'],result.session).replies.length,0);assert.equal(chat(['reset'],result.session).session.state,'WELCOME');});
test('catering enquiry hands off without marketing',()=>{const result=chat(['catering','Test Customer','27 Sep','50','Birthday','Vegetarian']);assert.equal(result.session.state,'HUMAN_HANDOFF');assert.equal(result.effect.details.guests,'50');});
test('website reservation and catering messages preserve full details for staff',()=>{const result=chat(['Hello Mozza Italia,\nI would like to reserve a table.\n\nPreferred outlet: Hyderabad\nName: Example']);assert.equal(result.effect.type,'handoff');assert.match(result.effect.details.request,/Hyderabad/);});
test('unknown state recovers',()=>{assert.equal(chat(['hello'],{...e.initialSession(),state:'INVALID'}).session.state,'WELCOME');});
test('official message payloads and service-window boundary',()=>{const reply=chat(['Hi']).replies[0];assert.equal(client.messagePayload(phone,reply).interactive.action.buttons.length,3);assert.equal(client.messagePayload(phone,{kind:'text',text:'Hello'}).messaging_product,'whatsapp');assert.equal(client.withinServiceWindow(now.toISOString(),now.getTime()+23*3600000),true);assert.equal(client.withinServiceWindow(now.toISOString(),now.getTime()+24*3600000),false);assert.equal(client.withinServiceWindow(undefined),false);assert.throws(()=>client.messagePayload(phone,{kind:'buttons',text:'x',choices:Array.from({length:4},()=>({id:'x',title:'x'}))}));});
test('all category and variant payloads respect interactive limits',()=>{for(const category of menuCategories){let s=chat(['order',`category:${category.id}`]);for(const reply of s.replies)client.messagePayload(phone,reply);for(const item of category.items){const r=chat([`item:${item.id}`],s.session);for(const reply of r.replies)client.messagePayload(phone,reply);}}});
test('webhook signatures use raw body and reject tampering',()=>{const body='{"test":true}',secret='test-only';const sig='sha256='+createHmac('sha256',secret).update(body).digest('hex');assert.equal(security.validSignature(body,sig,secret),true);assert.equal(security.validSignature(body+' ',sig,secret),false);assert.equal(security.validSignature(body,null,secret),false);assert.equal(security.validSignature(body,sig,''),false);});
function fakeStore(){const seen=new Set();let current;const effects=[];const replies=[];let failFlush=false;return {effects,replies,setFail(v){failFlush=v;},async seen(id){return seen.has(id);},async session(){return current?structuredClone(current):undefined;},async draft(){return checkout;},async commit(args){if(seen.has(args.p_message_id))return {duplicate:true};if((current?.version||0)!==args.p_version)return {retry:true};seen.add(args.p_message_id);current={state_payload:args.p_session,version:(current?.version||0)+1};if(args.p_effect)effects.push(args.p_effect);replies.push(args.p_replies);return {ok:true};},async flush(){if(failFlush)throw new Error('simulated Meta outage');}};}
test('persisted processing creates an order once across duplicate/concurrent delivery',async()=>{const store=fakeStore();const inputs=[...pizzaFlow,'checkout','pickup','Test Customer','confirm'];for(let i=0;i<inputs.length;i++){const event={id:`m${i}`,phone,input:inputs[i],timestamp:now.toISOString()};await Promise.all([processIncoming(event,store),processIncoming(event,store)]);}assert.equal(store.effects.filter(e=>e.type==='order').length,1);assert.match(store.effects.at(-1).reference,/^MI-/);});
test('Meta failure after commit retries replies without duplicating orders',async()=>{const store=fakeStore();const inputs=[...pizzaFlow,'checkout','pickup','Test Customer'];for(let i=0;i<inputs.length;i++)await processIncoming({id:`m${i}`,phone,input:inputs[i],timestamp:now.toISOString()},store);const event={id:'confirm-final',phone,input:'confirm',timestamp:now.toISOString()};store.setFail(true);await assert.rejects(()=>processIncoming(event,store));store.setFail(false);await processIncoming(event,store);assert.equal(store.effects.filter(e=>e.type==='order').length,1);});
test('expired or wrong-phone draft gives recovery without creating order',async()=>{const store=fakeStore();store.draft=async()=>undefined;await processIncoming({id:'draft',phone,input:security.draftToken(),timestamp:now.toISOString()},store);assert.equal(store.effects.length,0);assert.match(store.replies[0][0].text,/expired/);});
test('reservation is persisted once with MR reference',async()=>{const store=fakeStore();const future=new Date(Date.now()+86400000).toISOString().slice(0,10);const inputs=['reserve',future,'20:30','4','Test Customer','skip','confirm'];for(let i=0;i<inputs.length;i++)await processIncoming({id:`r${i}`,phone,input:inputs[i],timestamp:new Date().toISOString()},store);assert.equal(store.effects.length,1);assert.match(store.effects[0].reference,/^MR-/);assert.match(store.replies.at(-1)[0].text,/not confirmed/);});
test('API fallback validates inputs and uses trusted prices without credentials',async()=>{const {POST}=load('src/app/api/orders/route.ts');const request=new Request('http://localhost/api/orders',{method:'POST',headers:{Origin:'http://localhost','Content-Type':'application/json'},body:JSON.stringify(checkout)});const response=await POST(request);assert.equal(response.status,200);const payload=await response.json();assert.equal(payload.mode,'fallback');assert.match(payload.whatsappUrl,/wa.me/);assert.equal((await POST(new Request('http://localhost/api/orders',{method:'POST',body:'{}'}))).status,403);});
test('admin API fails closed without a configured secret',async()=>{const {GET}=load('src/app/api/admin/orders/route.ts');assert.equal((await GET(new Request('http://localhost/api/admin/orders'))).status,401);});

test('origin guard accepts browser host behind Next internal URL and rejects other origins',()=>{assert.equal(security.sameOrigin(new Request('http://localhost:3000/api/orders',{headers:{Host:'127.0.0.1:3000',Origin:'http://127.0.0.1:3000'}})),true);assert.equal(security.sameOrigin(new Request('http://localhost:3000/api/orders',{headers:{Host:'127.0.0.1:3000',Origin:'https://attacker.example'}})),false);});
test('central reservation/catering intent messages with details hand off intact',()=>{const {whatsappIntentMessage}=load('src/config/restaurant.ts');assert.equal(chat([whatsappIntentMessage('reservation')+'\nPreferred outlet: Shadnagar\nName: Test']).effect.type,'handoff');assert.equal(chat([whatsappIntentMessage('catering')+'\nEvent date: 2026-10-10']).effect.type,'handoff');});
async function withEnvironment(values,run){const previous={};for(const [key,value] of Object.entries(values)){previous[key]=process.env[key];process.env[key]=value;}try{return await run();}finally{for(const [key,value] of Object.entries(previous)){if(value===undefined)delete process.env[key];else process.env[key]=value;}}}
const fakeCloud={SUPABASE_URL:'https://example.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-only',WHATSAPP_PHONE_NUMBER_ID:'123456',WHATSAPP_ACCESS_TOKEN:'test-only',WHATSAPP_APP_SECRET:'test-only-app',WHATSAPP_VERIFY_TOKEN:'test-only-verify',WHATSAPP_API_VERSION:'v99.0'};
test('website draft mode stores trusted summary and returns only short reference',async()=>{const original=globalThis.fetch;let submitted;try{globalThis.fetch=async(url,options)=>{assert.match(url,/rpc\/create_order_draft$/);submitted=JSON.parse(options.body);return Response.json({token:submitted.p_token});};await withEnvironment(fakeCloud,async()=>{const {POST}=load('src/app/api/orders/route.ts');const response=await POST(new Request('http://localhost/api/orders',{method:'POST',headers:{Origin:'http://localhost','Idempotency-Key':'test-key-000000000000000000000001'},body:JSON.stringify({...checkout,subtotal:1})}));const body=await response.json();assert.equal(body.mode,'draft');assert.equal(submitted.p_checkout.subtotal,pizza.sizes[0].price*2);const message=new URL(body.whatsappUrl).searchParams.get('text');assert.match(message,/MI-DRAFT-[A-F0-9]{32}/);assert.doesNotMatch(message,/Margarita|Test Customer|9876543210/);});}finally{globalThis.fetch=original;}});
test('database outage falls back without claiming a saved order',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>{throw new Error('simulated outage');};await withEnvironment(fakeCloud,async()=>{const {POST}=load('src/app/api/orders/route.ts');const response=await POST(new Request('http://localhost/api/orders',{method:'POST',headers:{Origin:'http://localhost','Idempotency-Key':'test-key-000000000000000000000002'},body:JSON.stringify(checkout)}));const result=await response.json();assert.equal(result.mode,'fallback');assert.match(result.note,/No backend order/);});}finally{globalThis.fetch=original;}});
test('webhook verification, malformed signed payload and wrong phone filtering',async()=>{await withEnvironment(fakeCloud,async()=>{const webhook=load('src/app/api/whatsapp/webhook/route.ts');assert.equal((await webhook.GET(new Request('http://localhost/api/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=test-only-verify&hub.challenge=12345'))).status,200);assert.equal((await webhook.GET(new Request('http://localhost/api/whatsapp/webhook?hub.mode=subscribe&hub.verify_token=wrong'))).status,403);const post=body=>webhook.POST(new Request('http://localhost/api/whatsapp/webhook',{method:'POST',headers:{'x-hub-signature-256':'sha256='+createHmac('sha256',fakeCloud.WHATSAPP_APP_SECRET).update(body).digest('hex')},body}));assert.equal((await post('null')).status,400);assert.equal((await post(JSON.stringify({object:'whatsapp_business_account',entry:[{changes:[{field:'messages',value:{metadata:{phone_number_id:'other'},messages:[{id:'x'}]}}]}]}))).status,200);assert.equal((await webhook.POST(new Request('http://localhost/api/whatsapp/webhook',{method:'POST',body:'{}'}))).status,403);});});
test('free-form sender refuses expired service window before network call',async()=>{await assert.rejects(()=>client.sendReply(phone,{kind:'text',text:'test'},'2000-01-01T00:00:00Z'),/Approved template required/);});
