import type {CSSProperties} from 'react';
import {FoodShape} from './FoodShape';
import {IngredientLayer} from './IngredientLayer';
import {animationAssets,ingredientAssets} from '@/data/menu-animation-data';
import {Steam} from './RiceReveal';
import type {SceneProps} from './types';
const delay=(i:number)=>({'--delay':`${.35+i*.22}s`,'--angle':`${(i%3-1)*16}deg`} as CSSProperties);
export function FriesAssembly({config}:SceneProps){return <div className="fa-composition fa-fries"><FoodShape kind="plate" className="build-plate"/>{[0,1,2,3,4].map(i=><FoodShape key={i} kind={config.variant==='wedges'?'wedge':'fries'} className={`fries-group fries-group-${i}`} color={config.variant==='salted'?'#f2c558':'#e4ae45'} style={delay(i)}/>)}{config.flags?.includes('cheese')&&<svg className="fries-pour" viewBox="0 0 400 320"><path className="fries-stream" d="M215 0 V144" fill="none" stroke="#f3c542" strokeWidth="10"/><path d="M215 144 Q130 153 255 168 Q308 180 143 201 Q108 211 270 224" fill="none" stroke="#f3c542" strokeWidth="14" strokeLinecap="round" pathLength="1"/></svg>}{config.flags?.filter(f=>f==='chicken'||f==='paneer').map(f=><IngredientLayer key={f} src={ingredientAssets[f as 'chicken'|'paneer']} className="fries-topping"/>)}{config.variant!=='cheesy'&&<div className="fries-seasoning" aria-hidden="true">{[0,1,2,3,4].map(i=><i key={i} style={delay(i)}/>)}</div>}</div>;}
export function BucketFill({config}:SceneProps){const count=config.flags?.includes('large')?5:3;return <div className="fa-composition fa-bucket"><FoodShape kind="bucket" className="bucket-back"/>{Array.from({length:count},(_,i)=><IngredientLayer key={i} src={config.variant==='mixed'?[animationAssets.chicken.drumstick,animationAssets.chicken.wing,animationAssets.chicken.popcorn][i%3]:animationAssets.chicken.wing} className={`bucket-piece bucket-piece-${i}`} style={{'--delay':`${.4+i*.3}s`,'--angle':`${i*19-25}deg`}}/>)}{config.flags?.includes('fries')&&<FoodShape kind="fries" className="bucket-fries"/>}<div className="bucket-front"><span>MOZZA ITALIA</span></div>{config.flags?.includes('dip')&&<FoodShape kind="bowl" color="#ddd3ac" className="bucket-dip"/>}</div>;}
export function BreadBuild({config}:SceneProps){const cheese=config.flags?.includes('cheese');return <div className={`fa-composition fa-bread ${config.variant==='stuffed'?'is-stuffed':''}`}><FoodShape kind="plate" className="build-plate"/>{[0,1,2].slice(0,config.variant==='stuffed'?2:3).map(i=><div key={i} className={`bread-slice bread-slice-${i}`} style={delay(i)}><FoodShape kind="bread"/>{cheese&&<span className="bread-cheese"/>}{config.flags?.includes('paneer')&&<IngredientLayer src={ingredientAssets.paneer} className="bread-filling"/>}{config.flags?.includes('chicken')&&<IngredientLayer src={ingredientAssets.chicken} className="bread-filling"/>}</div>)}{cheese&&<svg className="bread-stretch" viewBox="0 0 400 320"><path d="M166 190 Q190 161 229 137 M168 198 Q196 168 235 141" fill="none" stroke="#f4d783" strokeWidth="4"/></svg>}<Steam/></div>;}
export function SaladBuild({config}:SceneProps){return <div className="fa-composition fa-salad"><FoodShape kind="bowl" className="salad-bowl" color="#a5b292"/>{[0,1,2,3,4].map(i=><FoodShape key={i} kind="leaf" color={i%2?'#91ab48':'#537c3c'} className={`salad-leaf salad-leaf-${i}`} style={delay(i)}/>)}{config.flags?.includes('feta')&&[0,1,2].map(i=><span key={i} className={`salad-feta salad-feta-${i}`}/>)}{config.variant==='non-veg'&&<IngredientLayer src={ingredientAssets.chicken} className="salad-protein"/>}{config.variant==='egg'&&<FoodShape kind="egg" className="salad-protein"/>}{config.flags?.includes('dressing')&&<svg className="salad-dressing" viewBox="0 0 400 320"><path d="M140 128 Q240 115 183 143 Q128 161 262 166" stroke="#d9bd65" strokeWidth="3" fill="none" pathLength="1"/></svg>}</div>;}
export function SnackBuild({config}:SceneProps){return <div className="fa-composition fa-snacks"><FoodShape kind="plate" className="build-plate"/>{[0,1,2,3].map(i=><FoodShape key={i} kind="patty" variant={config.variant==='chicken'?'chicken':'veg'} className={`snack-piece snack-piece-${i} ${config.variant==='fingers'?'snack-finger':''}`} style={delay(i)}/>)}</div>;}
export function IceCreamBuild({config}:SceneProps){return <div className="fa-composition fa-icecream"><FoodShape kind="bowl" color="#d2b58c" className="icecream-cup"/><FoodShape kind="scoop" color={config.color} className="icecream-scoop"/></div>;}
export function SweetBuild({config}:SceneProps){const jamun=config.variant==='jamun',rabdi=config.variant==='rabdi'||config.flags?.includes('rabdi');return <div className="fa-composition fa-sweet"><FoodShape kind={rabdi?'bowl':'plate'} className="build-plate" color="#d7c28e"/>{rabdi&&<div className="rabdi-fill"/>}{jamun?[0,1,2].slice(0,config.flags?.includes('three')?3:2).map(i=><FoodShape key={i} kind="jamun" color="#a76b32" className={`jamun jamun-${i}`} style={delay(i)}/>):config.variant==='lava'?<FoodShape kind="lava" className="sweet-lava"/>:null}{config.flags?.includes('icecream')&&<FoodShape kind="scoop" color="#f5e6b9" className="sweet-scoop"/>}</div>;}
export function DipBuild({config}:SceneProps){return <div className="fa-composition fa-dips">{[0,1].map(i=><div key={i} className={`dip-cup dip-cup-${i}`}><FoodShape kind="bowl" color="#c8c5a5"/><span style={{background:config.variant==='mustard-chipotle'?(i?'#a6653d':'#c5a23f'):(i?'#d2a277':'#f3e7c8')}}/></div>)}</div>;}
export function ExtraBuild({config}:SceneProps){return <div className="fa-composition fa-extras"><FoodShape kind="plate" className="build-plate"/>{config.variant==='patty'?<FoodShape kind="patty" variant={config.garnish||"veg"} className="extra-serving"/>:<IngredientLayer src={config.variant==='paneer'?ingredientAssets.paneer:config.variant==='chicken'?ingredientAssets.chicken:animationAssets.burger.cheese} className="extra-serving"/>}</div>;}
export function GraphicFallback({config}:SceneProps){const family=config.family;return <div className="fa-composition fa-graphic-fallback"><FoodShape kind={family==='burger'?'bread':family?.includes('shake')||family==='mojito'||family==='cooler'?'bottle':family==='ice-cream'?'scoop':family==='rice'||family==='salad'?'bowl':family==='pizza'?'plate':'patty'} color={config.color||'#d7b15e'}/></div>;}
