'use client';
import { useEffect, useRef, type ReactNode } from 'react';
import { X } from 'lucide-react';
export function Modal({open,onClose,title,children,className='',onKeyDown,animated=false,sheet=false}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;className?:string;onKeyDown?:React.KeyboardEventHandler<HTMLDialogElement>;animated?:boolean;sheet?:boolean}) {
 const ref=useRef<HTMLDialogElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);const touch=useRef(0);
 const close=()=>{if(timer.current)return;if(!animated||window.matchMedia('(prefers-reduced-motion:reduce)').matches){onClose();return;}ref.current?.setAttribute('data-closing','true');timer.current=setTimeout(()=>{timer.current=null;onClose();},220);};
 useEffect(()=>{const el=ref.current;if(!el)return;if(open){el.removeAttribute('data-closing');el.showModal();const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{if(timer.current){clearTimeout(timer.current);timer.current=null;}el.close();document.body.style.overflow=prev;};}else el.close();},[open]);
 return <dialog ref={ref} className={`modal ${className}`} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===e.currentTarget)close();}} aria-label={title} onKeyDown={e=>{onKeyDown?.(e);if(e.defaultPrevented||e.key!=='Tab')return;const controls=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')).filter(el=>el.getClientRects().length);const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}><div className="modal-inner">{sheet&&<button className="sheet-handle" aria-label="Close item detail" onClick={close} onPointerDown={e=>{touch.current=e.clientY;e.currentTarget.setPointerCapture(e.pointerId);}} onPointerUp={e=>{if(e.clientY-touch.current>65)close();}}/>}<button className="icon-button modal-close" aria-label="Close dialog" onClick={close}><X/></button>{children}</div></dialog>;
}
